---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
    - name: app-container
      image: redis
      env:
        - name: SECRET_USERNAME
          value: ""
        - name: SECRET_PASSWORD
          value: ""
