---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    add: demo
    run: demo
spec:
  containers:
    - name: app-container
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
