---
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
    - name: app-resource
      image: kuard-amd64:1
      resources:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10