---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      containers:
        - name: app-container
          image: google/cloud-sdk:275.0.0-alpine
          command: ["gsutil"]
          args: ["-m", "rsync", "-dr", "gs://glow-sportradar/", "/data/input"]
      restartPolicy: Never